on:
  push:
    tags:
    - 'v*'

name: Upload Release Asset

env:
  CARGO_TERM_COLOR: always
    
jobs:
  release-linux:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v3
        continue-on-error: true
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-stable-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: rui314/setup-mold@v1
      - name: Build project
        run: cargo b --release
      - name: Make archive
        run: tar -C target/release -Jcvf yozuk-discord-x86_64-unknown-linux-gnu.tar.xz yozuk-discord
      - name: Make archive
        run: tar -C target/release -Jcvf yozuk-slack-x86_64-unknown-linux-gnu.tar.xz yozuk-slack
      - name: Make archive
        run: tar -C target/release -Jcvf yozuk-telegram-x86_64-unknown-linux-gnu.tar.xz yozuk-telegram
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} --generate-notes
        continue-on-error: true
      - name: Upload archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} *.tar.*
